### ISSUE TITLE
Be more accepting of bad dates and numbers with commas (was: Recover from horribly broken files better)

### ISSUE THREAD

**Issue by Wooble** [pitthsls/pycounter#15]
In a purportedly COUNTER XLSX report (no TSV was available, which itself is a violation of the standard...) from a vendor who shall remain anonymous, the Date Run field was stored in Excel as a date, not a "YYYY-MM-DD" string, which openpyxl "conveniently" converts to a datetime.date. 

Since pycounter expects to find a date string in that position, it blows up trying to do string operations.

It should DWIM instead, and use that date correctly (unless we add a strict mode that refuses to parse malformed COUNTER, then it should only do that in non-strict mode).

(Marked as enhancement instead of bug, since it's the data that's at fault, not the code...)

**Comment by godmar** [comment]
I see the same thing, a date_run entry in MM/DD/YYYY format in numerous real-world JR1s.

Would the developers entertain a PR to fix that?

**Comment by Wooble** [comment]
I came very close to starting to write a failing unit test for this issue
yesterday... I'd love a PR so I don't have to actually do it next week...

**Comment by godmar** [comment]
Let's talk about this first a bit. I have a pile of real-world JR1 I'm trying to help someone parse.
Check out this gist: https://gist.github.com/godmar/8e32645ddc7086494a04

This includes:
- accepting variations in date_run format.
- accepting variations in month (e.g. Jan-11, 11-Jan).
- accepting numbers with thousands-separators (1,000,000)
- ignoring lines that are all ,,,,,,,,,,,

Conceivably, these could all be done by default, unless they'd introduce ambiguity and/or unless standard checking is desired.

An "output" feature could then create a compliant report (I haven't checked if pycounter already has that).

Thoughts?

**Comment by Wooble** [comment]
For the last chunk, I'd prefer to use `format_stat()` to repeating the comma replacement and int() call; it's used everywhere else numbers are read (I think), but somehow I missed it there. I guess I haven't gotten a report recently with commas for those totals fields. (COUNTER 4 explicitly says you can't include any commas in any field, so I hope to never see one again, but I'm all for defensive programming anyway).

The latest releases do include output (COUNTER 4 only, but should convert existing COUNTER 3 reports correctly).

Everything else looks good to me. (Doesn't solve my Excel file datetime problem, of course, but I'm happy to fix that myself if I come across such a file again to test with.)

**Comment by godmar** [comment]
I see. So look at https://gist.github.com/godmar/8e32645ddc7086494a04#file-gistfile2-patch
This uses format_stat and it also accepts years in reports that have 12-Jan, etc.

**Comment by godmar** [comment]
Separate issue: what's your strategy of dealing with counter reports that are not UTF-8?
So far, for the random batch of JR1 reports I have, 195 parse ok with pycounter (with the patches in the gist). 328 fail to parse, the majority because the file is not UTF-8.

One strategy is to try to iconv the file before injection, which may work if the file's encoding is known.

pycounter right now seems to insist on valid UTF-8 for files ending in .csv.

What do you think the best strategy is?

**Comment by Wooble** [comment]
That gist looks great.

I'm going to open a separate issue for encoding (and retitle this one...)

**Comment by godmar** [comment]
Updated score is actually: 265 yes, 258 no with the latest patches related to format handling.

**Comment by Wooble** [comment]
I think this is more-or-less covered by the current codebase; feel free to open specific issues for any more cases that still aren't covered...
