### ISSUE TITLE
fetching of COUNTER 4 JR2 report using SUSHI not supported

### ISSUE THREAD

**Issue by beda42** [pitthsls/pycounter#93]
Hi,

I have seen that you have added support for JR2 reports, but from what I see this only relates to reading the TSV files in. When I try to download JR2 using SUSHI, the data is stored without the "Access Denied Category" column.
This also means that the data cannot be read back because of a "list index out of range" error - at least in my case where I download only one month of data. For more months, it would probably mean the first month would be skipped on read.
Could you please confirm this? Do you plan to add the JR2 support to SUSHI as well?

Thanks
Beda

**Comment by Wooble** [comment]
Thanks for reporting this. I think it would have been losing all of the data, not just the first month.

This "fix" probably needs some more work still; I'd like the sushiclient to also be able to actually export these reports and I don't think it's going to be able to handle that with the current fix although I haven't tested it yet.
